const STORAGE_KEY = 'buildvault-builds-v1';
let builds = [];
let activeBuildId = null;
const $ = s => document.querySelector(s);
const money = value => new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(Number(value)||0);
const escapeHTML = str => String(str||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const uid = () => crypto.randomUUID ? crypto.randomUUID() : Date.now().toString(36)+Math.random().toString(36).slice(2);

function load(){try{builds=JSON.parse(localStorage.getItem(STORAGE_KEY))||[]}catch{builds=[]}render()}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(builds));render()}
function price(build){return (build.components||[]).reduce((sum,c)=>sum+(Number(c.price)||0),0)}
function placeholder(){return '<div class="image-fallback">🖥</div>'}
function imageContent(src){return src ? `<img src="${escapeHTML(src)}" alt="" onerror="this.style.display='none';this.parentElement.classList.add('failed-image')">` : placeholder()}
function render(){
  const q=$('#searchInput').value.trim().toLowerCase(), sort=$('#sortSelect').value;
  let visible=builds.filter(b=>[b.title,b.description,(b.components||[]).map(c=>c.name+' '+c.category).join(' ')].join(' ').toLowerCase().includes(q));
  visible.sort((a,b)=> sort==='title'?a.title.localeCompare(b.title):sort==='price-high'?price(b)-price(a):sort==='price-low'?price(a)-price(b):new Date(b.updatedAt)-new Date(a.updatedAt));
  $('#buildCount').textContent=builds.length; $('#totalValue').textContent=money(builds.reduce((s,b)=>s+price(b),0));
  $('#buildGrid').innerHTML=visible.map((b,i)=>`<article class="build-card" style="animation-delay:${i*40}ms" data-id="${b.id}"><div class="build-image">${imageContent(b.image)}</div><button class="fav-button ${b.favorite?'active':''}" data-fav="${b.id}" title="Toggle favorite">★</button><div class="build-info"><h3>${escapeHTML(b.title)}</h3><p>${escapeHTML(b.description||'No description added')}</p><div class="card-bottom"><span>${money(price(b))}</span><span class="part-count">${(b.components||[]).length} parts</span></div></div></article>`).join('');
  $('#emptyState').hidden=visible.length>0; $('#buildGrid').hidden=visible.length===0;
}
function toast(message){const el=document.createElement('div');el.className='toast';el.textContent=message;$('#toastContainer').append(el);setTimeout(()=>{el.classList.add('out');setTimeout(()=>el.remove(),300)},2500)}
function openBuildForm(build){$('#buildForm').reset();$('#buildId').value=build?.id||'';$('#modalKicker').textContent=build?'EDIT BUILD':'NEW BUILD';$('#modalTitle').textContent=build?'Edit build':'Create a build';['title','description','image','notes'].forEach(k=>$('#'+k).value=build?.[k]||'');$('#favorite').checked=!!build?.favorite; previewImage();$('#buildModal').showModal()}
function previewImage(){const src=$('#image').value.trim();$('#imagePreview').innerHTML=src?`<img src="${escapeHTML(src)}" alt="Cover preview" onerror="this.remove();this.parentElement.innerHTML='<span>🖥</span><small>Image unavailable</small>'">`:'<span>🖥</span><small>Cover image preview</small>'}
function openDetail(id){activeBuildId=id; const b=builds.find(x=>x.id===id);if(!b)return;$('#detailTitle').textContent=b.title;$('#detailCover').innerHTML=imageContent(b.image);$('#detailDescription').textContent=b.description||'No description added.';$('#detailPrice').textContent=money(price(b));$('#detailNotes').textContent=b.notes||'No notes yet.';$('#notesSection').hidden=!b.notes;$('#componentCount').textContent=(b.components||[]).length;$('#componentsList').innerHTML=(b.components||[]).length?b.components.map(c=>`<div class="component-row"><span class="category-pill">${escapeHTML(c.category)}</span><div><div class="component-name">${escapeHTML(c.name)}</div>${c.details?`<div class="component-details">${escapeHTML(c.details)}</div>`:''}</div><span class="component-price">${money(c.price)}</span><div><button class="row-button" data-edit-component="${c.id}" title="Edit">✎</button><button class="row-button" data-delete-component="${c.id}" title="Delete">×</button></div></div>`).join(''):'<p class="component-details">No components yet. Add your first part above.</p>';$('#detailModal').showModal()}
function openComponentForm(component){$('#componentForm').reset();$('#componentId').value=component?.id||'';$('#componentKicker').textContent=component?'EDIT COMPONENT':'NEW COMPONENT';$('#componentModalTitle').textContent=component?'Edit component':'Add component';['category','name','details','price'].forEach(k=>$('#component'+k[0].toUpperCase()+k.slice(1)).value=component?.[k]??'');$('#componentModal').showModal()}

$('#newBuildBtn').onclick=()=>openBuildForm();$('.empty-create').onclick=()=>openBuildForm();
$('#searchInput').oninput=render;$('#sortSelect').onchange=render;$('#image').oninput=previewImage;
document.addEventListener('click',e=>{const close=e.target.closest('[data-close]');if(close){$('#'+close.dataset.close).close();return}const fav=e.target.closest('[data-fav]');if(fav){e.stopPropagation();const b=builds.find(x=>x.id===fav.dataset.fav);b.favorite=!b.favorite;b.updatedAt=new Date().toISOString();save();toast(b.favorite?'Added to favorites':'Removed from favorites');return}const card=e.target.closest('.build-card');if(card)openDetail(card.dataset.id);const edit=e.target.closest('[data-edit-component]');if(edit){openComponentForm(builds.find(b=>b.id===activeBuildId).components.find(c=>c.id===edit.dataset.editComponent))}const del=e.target.closest('[data-delete-component]');if(del&&confirm('Delete this component?')){const b=builds.find(x=>x.id===activeBuildId);b.components=b.components.filter(c=>c.id!==del.dataset.deleteComponent);b.updatedAt=new Date().toISOString();save();openDetail(b.id);toast('Component deleted')}});
$('#buildForm').onsubmit=e=>{e.preventDefault();const id=$('#buildId').value;const existing=builds.find(b=>b.id===id);const data={id:id||uid(),title:$('#title').value.trim(),description:$('#description').value.trim(),image:$('#image').value.trim(),notes:$('#notes').value.trim(),favorite:$('#favorite').checked,components:existing?.components||[],createdAt:existing?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()};if(existing)Object.assign(existing,data);else builds.push(data);save();$('#buildModal').close();toast(existing?'Build updated':'Build created');if(existing&&activeBuildId===id)openDetail(id)};
$('#editBuildBtn').onclick=()=>{const b=builds.find(x=>x.id===activeBuildId);$('#detailModal').close();openBuildForm(b)};
$('#addComponentBtn').onclick=()=>openComponentForm();
$('#componentForm').onsubmit=e=>{e.preventDefault();const b=builds.find(x=>x.id===activeBuildId),id=$('#componentId').value;const existing=b.components.find(c=>c.id===id);const c={id:id||uid(),category:$('#componentCategory').value.trim(),name:$('#componentName').value.trim(),details:$('#componentDetails').value.trim(),price:Math.max(0,Number($('#componentPrice').value)||0)};if(existing)Object.assign(existing,c);else b.components.push(c);b.updatedAt=new Date().toISOString();save();$('#componentModal').close();openDetail(b.id);toast(existing?'Component updated':'Component added')};
$('#deleteBuildBtn').onclick=()=>{const b=builds.find(x=>x.id===activeBuildId);if(confirm(`Delete “${b.title}”? This cannot be undone.`)){builds=builds.filter(x=>x.id!==activeBuildId);save();$('#detailModal').close();toast('Build deleted')}};
$('#exportBtn').onclick=()=>{const blob=new Blob([JSON.stringify({app:'BuildVault',version:1,builds},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='buildvault-backup.json';a.click();URL.revokeObjectURL(a.href);toast('Builds exported')};
$('#importBtn').onclick=()=>$('#importFile').click();$('#importFile').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const data=JSON.parse(await f.text()),items=Array.isArray(data)?data:data.builds;if(!Array.isArray(items))throw Error();if(!confirm(`Import ${items.length} build(s)? Your current builds will be kept.`))return;const known=new Set(builds.map(b=>b.id));items.forEach(b=>{if(!b||!b.title)return;b.id=known.has(b.id)?uid():(b.id||uid());b.components=Array.isArray(b.components)?b.components:[];b.updatedAt=b.updatedAt||new Date().toISOString();builds.push(b)});save();toast('Import complete')}catch{toast('That file is not a valid BuildVault export')}finally{e.target.value=''}};
load();
